export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const GET_CREATED_URL_SUCCESS = 'GET_CREATED_URL_SUCCESS';
export const GET_TOP_3_VISITED_URL = 'GET_TOP_3_VISITED_URL';
export const GET_HIT_COUNT_GROUP_BY_DATE = 'GET_HIT_COUNT_GROUP_BY_DATE';
export const CREATE_SHORT_URL_SUCCESS = 'CREATE_SHORT_URL_SUCCESS';